---
title: "'On Error' ステートメントは、'Using' ステートメント内では使用できません"
ms.date: 07/20/2015
f1_keywords:
- vbc36013
- bc36013
helpviewer_keywords:
- BC36013
ms.assetid: 5b399bf9-6595-46e0-a808-378f6c28568b
ms.openlocfilehash: 70e03a298bfe4d3898a5f8bb571735f6f73886f8
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 06/04/2020
ms.locfileid: "84378804"
---
# <a name="on-error-statements-are-not-valid-within-using-statements"></a>'On Error' ステートメントは、'Using' ステートメント内では使用できません
`On Error` ステートメントが `Using` ステートメント内で使用されていますが、このコンテキストには使用できません。  
  
 **エラー ID:** BC36013  
  
## <a name="to-correct-this-error"></a>このエラーを解決するには  
  
- `Try…Catch` ブロックなどの構造化エラー処理を `On Error` ステートメントの代わりに使用します。  
  
## <a name="see-also"></a>関連項目

- [On Error ステートメント](../language-reference/statements/on-error-statement.md)
- [Try/catch ブロックを使用して例外をキャッチする方法](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [Try...Catch...Finally ステートメント](../language-reference/statements/try-catch-finally-statement.md)
