---
title: "' ' は ' <name1> ' から継承されるため、' Catch ' ブロックに到達しませんでした。 <name2>"
ms.date: 07/20/2015
f1_keywords:
- BC42029
- vbc42029
helpviewer_keywords:
- BC42029
ms.assetid: 4bc84a84-ec7e-49db-8794-4fb71d36d5c0
ms.openlocfilehash: 560beddd1e9051c43d610fe893a55baa2a5c559a
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 06/04/2020
ms.locfileid: "84395650"
---
# <a name="catch-block-never-reached-because-name1-inherits-from-name2"></a>' ' は ' \<name1> ' から継承されるため、' Catch ' ブロックに到達しませんでした。 \<name2>
コード内の `Catch` ブロックに到達することはありません。  
  
 既定では、このメッセージは警告です。 警告を非表示にする方法や、警告をエラーとして扱う方法の詳細については、「 [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic)」を参照してください。  
  
 **エラー ID:** BC42029  
  
## <a name="to-correct-this-error"></a>このエラーを解決するには  
  
- 余分な `Catch` ブロックを削除します。  
  
## <a name="see-also"></a>関連項目

- [Try/catch ブロックを使用して例外をキャッチする方法](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [Try...Catch...Finally ステートメント](../language-reference/statements/try-catch-finally-statement.md)
